version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: base
  web:
    build: .
    command:  bash -c "python /usr/src/dm_rest/manage.py makemigrations &&
              python /usr/src/dm_rest/manage.py migrate &&
              python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres-data:
